<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>target-plantao</AssemblyName>
    <RootNamespace>TargetPlantao.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TargetPlantao.Core\TargetPlantao.Core.csproj" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TargetPlantao.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
